spring.application.name=tester

# spring.data.mongodb.uri=mongodb://localhost:27017/apitester

# Replace with your actual username, password and cluster URL from MongoDB Atlas.
spring.mongodb.uri=mongodb+srv://singhpriyansh1403_db_user:jbivZjaEiV8cKXky@cluster00.3jmtxae.mongodb.net/api_tester_db?retryWrites=true&w=majority

# mongodb+srv://singhpriyansh1403_db_user:<db_password>@cluster00.3jmtxae.mongodb.net/?appName=Cluster00

# This is the database name — Atlas will create it automatically when you first store data in it.
spring.mongodb.database=api_tester_db